name: Maven Publish

on:
  publish:
    types: [published]

jobs:
  publish-1.14.4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          with:
            ref: minecraft/1.14.4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish 1.14.4 artifacts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ASW_KEY }}
        run: |
          chmod +x gradlew
          ./gradlew publish
  publish-1.15.1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          with:
            ref: minecraft/1.15.1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish 1.15.1 artifacts
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ASW_KEY }}
        run: |
          chmod +x gradlew
          ./gradlew publish